name: Publish test reports
run-name: Publish test reports by @${{ github.actor }}

on:
  - workflow_call

jobs:
  publish:
  environment: GitHub_Api_Token
    runs-on: ubuntu-latest

    steps:

      - name: Download test reports
        uses: actions/download-artifact@v4
        with:
          name: test-reports
          path: test-reports

      - name: Publish test reports
        uses: 'GamuNetwork/devtools/test-reports-publisher@V1.2.9'
        with:
          test-reports-path: test-reports
          repository: ${{ github.repository }}
          branch: ${{ github.ref }}
        env:
          GH_TOKEN: ${{ secrets.GITHUBAPITOKEN }}

      - name: Cleanup
        run: rm -rf test-reports