name: Publish test reports
run-name: Publish test reports by @${{ github.actor }}

on:
  - workflow_call

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

      - name: Download test reports
        uses: actions/download-artifact@v4
        with:
          name: test-reports
          path: test-reports

      - name: Publish test reports
        uses: 'GamuNetwork/devtools/test-reports-publisher@V1.2.7'
        with:
          test-reports-path: test-reports
          repository: ${{ github.repository }}
          branch: ${{ github.ref }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Cleanup
        run: rm -rf test-reports