name: On push to main branch
on:
  push:
    branches:
      - main

# call the workflow unitTests on ubuntu-latest
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: temp
        run: echo "temp"

      # just to show that the workflow is running

