name: On push to main branch
on:
  push:
    branches:
      - main

# call the workflow unitTests on ubuntu-latest
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: temp
        run: echo "temp"

      # just to show that the workflow is running

